version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      chuA71YXz02aaWbDprMD4t4iJKyg4jBYXGvBqWRb1KwdkfcqA2oqRXDi27z/3BA6+GwKpwCMQq2ptWqCY5MOAMor3woIpwKHzasNfubPo04PKloIX+ClewWVBKSiZC0NqLFUJ8NcEv9qyUPi7gd92YYq27dKMn/hQnKch7Q4Lvg=
